server {

    listen 80;

    server_name localhost;

    root /var/www/html/frontend;

    index index.html index.php;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        alias /var/www/html/backend;

        location ~ \.php$ {
            fastcgi_pass php:9000;
            fastcgi_index logical.php;
            include fastcgi_params;

            fastcgi_param SCRIPT_FILENAME $request_filename;
        }
    }
}